# Example configuration file for use with Mihomo and mihomo-ctl or mihomoCC for macOS.
# Relies on remote DNS resolution of proxied queries to avoid DNS leaks.

# This YAML only requires a valid proxy server to work. Refer to mihomo wiki on how to add one:
# https://wiki.metacubex.one

proxy-groups:
  - name: PROXYGROUP                # Proxy group template
    type: select
    interval: 86400                 # Health check interval
    proxies:                        # Any proxies defined here can be selected from Zashboard (with a MATCH,PROXYGROUP rule) or defined in other rules
      - "ProxyName"                 # Replace the placeholder with your actual proxy's name

dns:
  enable: true
  respect-rules: false              # Do not enable with fake-ip
  prefer-h3: false                  # DNS-over-QUIC. Can be enabled if your nameserver supports it
  listen: '127.0.0.1:53'            # Local DNS, must be on port 53. You can define a real DNS (such as 223.5.5.5), but macOS may force some system queries to go there
  enhanced-mode: fake-ip            # Returns fake IPs for DNS queries. DIRECT and PROXY rules decide whether to resolve locally or remotely
  fake-ip-ttl: 1                    # TTL for fake IPs. Usually doesn't need higher values than 1
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter-mode: blacklist    # Blacklisted rules will get real IPs, resolved through nameserver
  fake-ip-filter:                   # Resolve real IPs for Apple system and LAN through nameserver
    - rule-set:🍏 Apple
    - rule-set:🏠 LAN
  ipv6: false
  default-nameserver:               # Resolve IPs for other nameservers. Must be a real IP or a URL containing a real IP (if you want DoH/DoT)
    - https://223.5.5.5/dns-query
  nameserver:                       # Resolve IPs for domains in DIRECT rulesets and fake-ip-filter
    - https://223.5.5.5/dns-query
  fallback: []                      # Since proxied domains are resolved remotely, you're unlikely to need this

tun:                                # Route all traffic through Mihomo. Requires root
  enable: true
  stack: system                     # Can be set to gvisor, system, mixed. Recommended priority is system > mixed > gvisor. mixed requires mixed-port (default: 7890)
  dns-hijack:                       # Hijack DNS queries system-wide and forward them to Mihomo's listener (which decides whether to resolve locally or remotely)
    - any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  route-exclude-address:
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12
    - fc00::/7

# Zashboard (web UI for Mihomo, can be called from mihomoCC)
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
external-ui: ~/.config/mihomo/ui
external-controller: 127.0.0.1:9090
secret: ""

# Rulesets for blocking ads and routing Apple system and LAN directly
rule-providers:
  📢 Ads:
    type: http
    path: "./rules/ads.yaml"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Advertising/Advertising_Domain.yaml"
    interval: 86400
    behavior: domain
    format: yaml

  🍏 Apple:
    type: http
    path: "./rules/apple.yaml"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple_Classical_No_Resolve.yaml"
    interval: 86400
    behavior: classical
    format: yaml

  🏠 LAN:
    type: http
    path: "./rules/lan.yaml"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan_No_Resolve.yaml"
    interval: 86400
    behavior: classical
    format: yaml

rules:
- RULE-SET,🏠 LAN,DIRECT
- RULE-SET,🍏 Apple,DIRECT
- RULE-SET,📢 Ads,REJECT
- MATCH,PROXYGROUP
